export type Game = {
  id: string;
  slug: string;
  title: string;
  description: string;
  route: string;
  gradient: string;
  accentColor: string;
  tags: string[];
  icon?: string;
};

export const GAMES: Game[] = [
  {
    id: "001",
    slug: "candy-fiesta",
    title: "Candy Fiesta",
    description: "Match-3 de candies con combos especiales, cascadas y 8 niveles de dificultad creciente.",
    route: "/game",
    gradient: "linear-gradient(180deg, #1565c0 0%, #7b2fa8 45%, #c2185b 100%)",
    accentColor: "#f7c500",
    tags: ["Match-3", "Puzzle"],
  },
  {
    id: "002",
    slug: "road-rush",
    title: "Road Rush",
    description: "Esquiva el tráfico cambiando de carril. La velocidad y los carriles aumentan con la distancia recorrida.",
    route: "/road-rush",
    gradient: "linear-gradient(180deg, #0f0f1a 0%, #1c1c2a 50%, #0f3460 100%)",
    accentColor: "#00d4ff",
    tags: ["Dodge", "Endless"],
  },
  {
    id: "003",
    slug: "pixel-run",
    title: "Pixel Run",
    description: "Plataformero de acción: salta, corre y elimina enemigos en 7 mundos únicos con controles táctiles.",
    route: "/pixel-run",
    gradient: "linear-gradient(180deg, #1b5e20 0%, #2e7d32 50%, #558b2f 100%)",
    accentColor: "#ffeb3b",
    tags: ["Plataformas", "Aventura"],
  },
  {
    id: "004",
    slug: "star-assault",
    title: "Star Assault",
    description: "Shooter espacial vertical: conquista 16 mundos alienígenas con 4 tipos de munición, tienda de naves y jefes épicos con mecánicas únicas.",
    route: "/star-assault",
    gradient: "linear-gradient(180deg, #000010 0%, #001040 50%, #000520 100%)",
    accentColor: "#00e5ff",
    tags: ["Shooter", "Acción"],
  },
  {
    id: "005",
    slug: "stack-tower",
    title: "Stack Tower",
    description: "Apila bloques con precisión perfecta. ¡Cada milímetro cuenta!",
    route: "/stack-tower",
    gradient: "from-blue-600 to-violet-600",
    accentColor: "#7c3aed",
    tags: ["Skill", "Precisión", "Mobile"],
    icon: "/games/stack-tower/icon.svg",
  },
  {
    id: "006",
    slug: "bubble-pop",
    title: "Bubble Pop",
    description: "Dispara burbujas y forma combos explosivos de colores.",
    route: "/bubble-pop",
    gradient: "from-pink-500 to-rose-500",
    accentColor: "#f43f5e",
    tags: ["Puzzle", "Match-3", "Mobile"],
    icon: "/games/bubble-pop/icon.svg",
  },
  {
    id: "007",
    slug: "snake-evo",
    title: "Snake Evo",
    description: "La serpiente clásica con obstáculos y power-ups evolutivos.",
    route: "/snake-evo",
    gradient: "from-green-500 to-emerald-600",
    accentColor: "#10b981",
    tags: ["Clásico", "Arcade", "Mobile"],
    icon: "/games/snake-evo/icon.svg",
  },
  {
    id: "008",
    slug: "brick-blitz",
    title: "Brick Blitz",
    description: "Rompe ladrillos con estilo. Power-ups, combos y 15 niveles.",
    route: "/brick-blitz",
    gradient: "from-orange-500 to-red-500",
    accentColor: "#ef4444",
    tags: ["Arcade", "Acción", "Mobile"],
    icon: "/games/brick-blitz/icon.svg",
  },
  {
    id: "009",
    slug: "fruit-slash",
    title: "Fruit Slash",
    description: "Corta frutas al vuelo. ¡Cuidado con las bombas!",
    route: "/fruit-slash",
    gradient: "from-lime-500 to-green-600",
    accentColor: "#84cc16",
    tags: ["Acción", "Touch", "Mobile"],
    icon: "/games/fruit-slash/icon.svg",
  },
  {
    id: "010",
    slug: "jump-hero",
    title: "Jump Hero",
    description: "Salta infinitamente hacia las estrellas. ¿Hasta dónde llegas?",
    route: "/jump-hero",
    gradient: "from-sky-500 to-blue-600",
    accentColor: "#0ea5e9",
    tags: ["Endless", "Plataformas", "Mobile"],
    icon: "/games/jump-hero/icon.svg",
  },
  {
    id: "011",
    slug: "merge-2048",
    title: "Merge 2048",
    description: "Fusiona tiles y llega al 2048. Desbloquea poderes en el camino.",
    route: "/merge-2048",
    gradient: "from-amber-400 to-orange-500",
    accentColor: "#f59e0b",
    tags: ["Puzzle", "Estrategia", "Mobile"],
    icon: "/games/merge-2048/icon.svg",
  },
  {
    id: "012",
    slug: "color-switch",
    title: "Color Switch",
    description: "Pasa por el color correcto. Un error y todo termina.",
    route: "/color-switch",
    gradient: "from-red-500 to-yellow-500",
    accentColor: "#eab308",
    tags: ["Reflejos", "Skill", "Mobile"],
    icon: "/games/color-switch/icon.svg",
  },
  {
    id: "013",
    slug: "tap-fever",
    title: "Tap Fever",
    description: "Toca los círculos antes de que desaparezcan. ¡Combos al máx!",
    route: "/tap-fever",
    gradient: "from-fuchsia-500 to-purple-600",
    accentColor: "#a855f7",
    tags: ["Reflejos", "Touch", "Mobile"],
    icon: "/games/tap-fever/icon.svg",
  },
  {
    id: "014",
    slug: "gravity-ball",
    title: "Gravity Ball",
    description: "Guía la bola por laberintos con gravedad. 20 niveles.",
    route: "/gravity-ball",
    gradient: "from-indigo-500 to-blue-700",
    accentColor: "#6366f1",
    tags: ["Puzzle", "Física", "Mobile"],
    icon: "/games/gravity-ball/icon.svg",
  },
];
